### PR TITLE
Assignement 3 Tribout Antoine

### PR DESCRIPTION
**Pull request by atribout**

### CODE REVIEW

**Comment by atribout** [comment]
Assignement 3 Tribout

**Comment by dgarijo** [comment]
@ocorcho

**Comment by atribout** [comment]
Hi can I have some returns on my work please ?

**Comment by ocorcho** [comment]
Sure. I will be releasing the right answers next week, so that you can compare. For the time being, we just accept them so that they are included in the repository with the original timestamp.

**Pull request merged**
